config/routes.rb
Kosmyka::Application.routes.draw do
  resources :questions


  devise_for :admins

  resources :projects

  get "services/index"

  get "company/index"

  resources :contacts

  root to: 'home#index'

  get "home/index"

 end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :message, :name, :phone

  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  PHONE_REGEX = /^\(?([0-9]{2,4})\)?[-. ]?([0-9]{3,4})[-. ]?([0-9]{0,4})$/

  validates :name, :presence => true, :length => { :maximum => 200 }
  validates :phone, :presence => true, :length => { :maximum => 16 }, :format => PHONE_REGEX
  validates :email, :presence => true, :length => { :maximum => 100 }, :format => EMAIL_REGEX
  validates :message, :presence => true, :length => { :maximum => 1000 }
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :areas, :client, :description, :launched, :name, :tecnologies, :kind, :url, :image, :screenshots_attributes

  has_many :screenshots

  accepts_nested_attributes_for :screenshots, :allow_destroy => true

  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :image, ImageUploader

  def previous_project
    self.class.first(:conditions => ["name < ?", name], :order => "name desc")
  end

  def next_project
    self.class.first(:conditions => ["name > ?", name], :order => "name asc")
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer, :question
end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base
  attr_accessible :screenshot

  belongs_to :project

  mount_uploader :screenshot, ScreenshotUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def bodyid
    @bodyid = params[:controller].parameterize
  end

  def bodyclass
    @action = params[:action].parameterize

    if params[:controller] == 'home' && params[:action] == 'index'
      @front = 'front'
    else
      @front = 'not-front'
    end

 #   if current_admin
 #     @admin = 'logged-in'
 #   else
 #     @admin = 'not-logged-in'
 #   end

    @bodyclass = @action + ' ' + @front #+ ' ' + @admin
  end

  helper_method :bodyid
  helper_method :bodyclass

end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def index
  end
end

app/controllers/contacts_controller.rb
#coding: utf-8
class ContactsController < InheritedResources::Base
  before_filter :authenticate_admin!, except: [:new, :create]

  def create
    @contact = Contact.new(params[:contact])

    create! do |success, failure|
      success.html do
        NotificationsMailer.new_contact(@contact).deliver

        flash[:notice] = "Tu mensaje fue enviado con éxito."
        redirect_to new_contact_path
      end

      failure.html do
        flash[:notice] = "No se envió el mensaje, corrige los campos y vuelve a intentar."
        render :action => "new"
      end

    end
  end

  def index
    @contacts = Contact.order("created_at ASC").paginate(:page => params[:page], :per_page => 30)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @projects = Project.order("launched DESC").limit(12)
    @contact = Contact.new
  end
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  before_filter :authenticate_admin!, except: [:index, :show]

  def index
    @projects = Project.order("launched DESC")
  end
end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base
  before_filter :authenticate_admin!, except: [:index]
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def encabezado_1
    '
      <div id="content-top" class="container-fluid">
        <div class="row-fluid">
          <div id="parallaxContainer" class="span12">'.html_safe
    # 3 divs
  end

  def encabezado_2(image1)
    image_tag "#{image1}"
  end

  def encabezado_3(title1)
    "#{'</div>
      <div id="content-middle">
      <h1 class="page-title">' + title1 +'</h1>'}".html_safe

    # 1 div
  end

  def encabezado_4(bootstrap_span)
    "#{'<div class="container-fluid region simple"><div class="' + bootstrap_span + ' main-section-page">'}".html_safe
    # 2 divs
  end

  def encabezado_5(title2)
    if title2 != 'false'
      "#{'<h2 class="title region-title">' + title2 + '</h2>'}".html_safe
    end
  end

  def closing_tags
    "</div></div></div></div></div>".html_safe
  end



  def encabezado(image1, title1, title2, bootstrap_span)
    encabezado_1 + encabezado_2(image1) + encabezado_3(title1) + encabezado_4(bootstrap_span) + encabezado_5(title2)
  end

  # PARAGRAPH
  def paragraph(text)
    "#{sanitize(simple_format(text), :tags => %w(p i br b))}".html_safe
  end

  def paragraph_truncate(text, length)
    "#{sanitize(simple_format(truncate(text, :length => length)), :tags => %w(p i br b))}".html_safe
  end

end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/company/_sidebar_first.html.haml
.span6
  %h2.title.region-title
    = image_tag 'img-tecnologias.png', class: 'not-full'
    %br
    Tecnologías

  %p
    Trabajamos basados en la filosofía “DRY” siglas en inglés de “Don’t Repeat Yourself”, que básicamente se trata de no repetir el mismo código mientras sea posible, de esta manera se adelgaza la cantidad de líneas de código y lo más importante, tenemos un código fácil de mantener y actualizar, facilitando y agilizando los futuros cambios que necesiten nuestros clientes.

  %p
    Trabajamos con herramientas espectaculares como Ruby on Rails y muchos gems geniales para crear las páginas y aplicaciones webs, la parte visual la diseñamos en Photoshop e Illustrator y usamos un flujo de trabajo muy eficiente con github y capistrano, nos encanta Nginx como servidor web y Unicorn como medio entre Rails y Nginx. Nuestra base de datos favorita es MySQL y también trabajamos con otras más exóticas como Redis.

  %p
    Armamos todo con Twitter Bootstrap, y usamos Haml para generar el HTML, junto con Sass y a veces Less para generar el CSS.

  %p
    Usamos Jquery para implementar esos sliders, slideshow, entre otros widgets que encantan a nuestros clientes.

  %p
    Todo esto lo escribimos en Vim, porque es simplemente el mejor editor de texto que existe en el mundo.

app/views/company/_sidebar_second.html.haml
.span6
  %h2.title.region-title
    = image_tag 'img-mercadeo.png', class: 'not-full'
    %br
    RED DE MERCADEO

  %p
    Tenemos para ti un negocio que sabemos te va a interesar, desde el momento que compras el desarrollo completo de una página web con nosotros, puedes empezar a ganar dinero. Es muy simple, al recomendar nuestro servicio con un colega, familiar o amigo, apenas cerremos contrato con esa persona, te pagaremos automáticamente. Podrás tener 2 recomendados debajo tuyo, y cada uno de estos podrá tener 2 recomendados debajo de cada uno de ellos y así sucesivamente. Además de ganar el bono inmediato por la recomendación, ganarás dinero también por cada recomendación que hagan las personas que están debajo tuyo. Así nosotros venderemos un montón y tú ganarás dinero fácilmente.
  %p
    Si estás interesado, ponte en contacto con nosotros y te brindremos toda la información al respecto.


  %h2.title.region-title
    = image_tag 'img-staff.png', class: 'not-full'
    %br
    STAFF
  %p
    Nuestro equipo se ha instruido con cursos en el prestigioso instituto “Caelum” en Brasil, compramos una buena cantidad de libros técnicos de Amazon sobre los temas que desarrollamos, somos principalmente autodidáctas y nuestro aprendizaje es continuo.

app/views/company/index.html.haml
#preload-v
#content-top.container-fluid
  .row-fluid
    #parallaxContainer.span12
      = image_tag 'img-servicios.jpg'
#content-middle
  %h1.page-title
    = I18n.t('services.index')
  .container.region.simple
    .row
      .span12.main-section-page
        %h2.title.region-title
          = image_tag 'img-rocket.png', class: 'not-full'
          %br
          Kosmyka Soluciones Informáticas E.I.R.L.
        %p
          Kosmyka es una pequeña empresa, localizada en Lima, fundada en el 2012, que nace de la necesidad de llenar un nicho en el mercado de los servicios en línea, brindando productos simples, fáciles de usar, enfocándonos en una estética moderna.

        %p
          Le damos un valor agregado a la sociedad a través de los servicios que damos. Nuestra misión es hacer del manejo de la marca en internet de cada uno de nuestros clientes una tarea fácil, haciendo del día a día de ellos más feliz.

        %p
          “Todo es simple hasta que uno lo hace complicado”

          %br
          Utilizamos tecnologías de punta para realizar y entregar proyectos ambiciosos a los usuarios. Transformamos sistemas complicados en interfaces muy sencillas, cambiamos el look & feel de tu producto o servicio por una experiencia de usuario eficiente que atrae y genera usuarios recurrentes.
        %p
          Nuestra meta es una variable que cambia todo el tiempo, crecer en conocimientos, estar al día con las tecnologías que nos permitan ser más felices trabajando en tus proyectos, resolviendo tus problemas de manera más eficiente y rápida.
        %p
          En el auge económico en el que se encuentra el Perú, es nuestra visión, consolidarnos como una empresa líder en desarrollo web, respaldando a nuestros clientes con la confianza de un portafolio lleno de casos de éxito.
      = render 'sidebar_first'
      = render 'sidebar_second'

app/views/contacts/_form.html.haml
= form_for @contact, :html => { :class => 'form-horizontal' } do |f|
  .span5.offset1
    .field
      = f.label :name, class: 'span3'
      = f.text_field :name, class: 'span9'
    .field
      = f.label :email, class: 'span3'
      = f.text_field :email, class: 'span9'
    .field
      = f.label :phone, class: 'span3'
      = f.text_field :phone, class: 'span9'
  .span5
    .field
      = f.label :message, class: 'span3'
      = f.text_area :message, class: 'span9'
    .actions
      = f.submit t('contact.submit')




-#
  = form_for @contact, :html => { :class => 'form-horizontal' } do |f|
    .control-group
      = f.label :name, :class => 'control-label'
      .controls
        = f.text_field :name, :class => 'text_field'
    .control-group
      = f.label :email, :class => 'control-label'
      .controls
        = f.text_field :email, :class => 'text_field'
    .control-group
      = f.label :phone, :class => 'control-label'
      .controls
        = f.text_field :phone, :class => 'text_field'
    .control-group
      = f.label :message, :class => 'control-label'
      .controls
        = f.text_area :message, :class => 'text_area'
    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), contacts_path, :class => 'btn'

app/views/contacts/edit.html.haml
- model_class = Contact
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/contacts/index.html.haml
- model_class = Contact
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:phone)
      %th= model_class.human_attribute_name(:message)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @contacts.each do |contact|
      %tr
        %td= link_to contact.id, contact_path(contact)
        %td= contact.name
        %td= contact.email
        %td= contact.phone
        %td= contact.message
        %td=l contact.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_contact_path(contact), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), contact_path(contact), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_contact_path, :class => 'btn btn-primary'

app/views/contacts/new.html.haml
- model_class = Contact
= encabezado('img-contacto.jpg', I18n.t('contact.title'), I18n.t('contact.heading'), 'span10 offset1')

.row.contact-info
  .span10
  .span5
    = image_tag 'icon-info.png', class: 'not-full'
    INFO@KOSMYKA.COM
  .span5.offset1
    = image_tag 'icon-face.png', class: 'not-full'
    = '/KOSMYKAweb'
  .span5
    = image_tag 'icon-mobile.png', class: 'not-full'
    951754033
  .span5.offset1
    = image_tag 'icon-twitter.png', class: 'not-full'
    @KOSMYKA

= closing_tags

#content-bottom.container-fluid
  .region.form-region
    .row-fluid
      .span12
        %h2.title
          = I18n.t('contact.legend')
      .row-fluid
        = render :partial => "form"






-#
  .page-header
    %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human

app/views/contacts/show.html.haml
- model_class = Contact
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @contact.name
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @contact.email
%p
  %strong= model_class.human_attribute_name(:phone) + ':'
  %br
  = @contact.phone
%p
  %strong= model_class.human_attribute_name(:message) + ':'
  %br
  = @contact.message

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), contacts_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_contact_path(@contact), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), contact_path(@contact), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/_menu.html.haml
.container.nav-collapse
  %ul.nav
    %li
      = link_to_unless_current I18n.t("projects.title"), projects_path do
        %span
          = I18n.t("projects.title")
    %li
      = link_to_unless_current I18n.t("questions.title"), questions_path do
        %span
          = I18n.t("questions.title")
    %li
      = link_to_unless_current I18n.t("services.title"), services_index_path do
        %span
          = I18n.t("services.title")
    %li
      = link_to_unless_current I18n.t("company.title"), company_index_path do
        %span
          = I18n.t("company.title")
    %li
      = link_to_unless_current I18n.t("contact.title"), new_contact_path do
        %span
          = I18n.t("contact.title")

app/views/layouts/application.html.haml
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7] <html class="no-js ie6 lt-ie9 lt-ie8 lt-ie7 lt-ie10 ie" lang="en">
/[if IE 7] <html class="no-js ie7 lt-ie9 lt-ie8 lt-ie10 ie" lang="en">
/[if IE 8] <html class="no-js ie8 lt-ie9 lt-ie10 ie" lang="en">
/[if IE 9] <html class="no-js ie9 lt-ie10 ie" lang="en">
/ Consider adding a manifest.appcache: h5bp.com/d/Offline
/ [if gt IE 9]><!
%html.no-js.gt-ie9.non-ie{:lang => "es"}
  / <![endif]
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Kosmyka | Diseñamos y programamos páginas y aplicaciones web dinámicas"
    = csrf_meta_tags
    %meta(name="keywords" content="Cotizacion pagina web, diseño pagina web")
    %meta(name="description" content="Diseñamos y programamos páginas y aplicaciones web dinámicas, con responsive design y ruby on rails.")
    %meta(name="googlebot" content="index,follow")
    %meta(name="robots" content="index,follow")
    %meta(name="Revisit-After" content="7 days")
    %meta(name="city" content="Lima")
    %meta(name="country" content="Peru")
    %meta(name="state" content="Lima")
    %meta(name="subject" content="Web Design")
    %meta(name="author" content="Kosmyka")
    %meta(name="copyright" content="&copy; Todos los derechos reservados.")
    %meta(name="geo.placename" content="Lima, Peru")
    %meta(name="geo.region" content="PE-Lima")
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application"
    = yield :css
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")

    = javascript_include_tag "application"
    = yield :javascript

    = auto_discovery_link_tag(:atom, projects_url(format: "atom"))

  %body{id: bodyid, class: bodyclass}
    %header
      = image_tag 'barra.jpg', class: 'barra'
      .navbar.navbar-fluid-top
        .navbar-inner
          .container-fluid
            %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to image_tag('logo.png'), '/', class: 'brand'
            = render 'layouts/menu'

    %section#content
      .container
        = render 'layouts/notices'
      = yield

    %footer.container-fluid.region
      .row-fluid
        %h2.element-invisible Footer

      .row-fluid
        #footer.span10
          .span2.redes-sociales-share
            = render 'shared/share'
          .span4.redes-sociales.contador
            = render 'shared/redes_sociales_contador'
          .span4.offset2.mail-us
            = link_to 'info@kosmyka.com', 'info@kosmyka', target: '_blank'

    = render 'shared/google_analytics'

app/views/projects/_form.html.haml
= nested_form_for @project, :html => { :multipart => true, :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :client, :class => 'control-label'
    .controls
      = f.text_field :client, :class => 'text_field'
  .control-group
    = f.label :launched, :class => 'control-label'
    .controls
      = f.date_select :launched, :class => 'date_select'
  .control-group
    = f.label :areas, :class => 'control-label'
    .controls
      = f.text_field :areas, :class => 'text_field'
  .control-group
    = f.label :tecnologies, :class => 'control-label'
    .controls
      = f.text_field :tecnologies, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :url, :class => 'control-label'
    .controls
      = f.text_field :url, :class => 'text_field'
  .control-group
    = f.label :kind, :class => 'control-label'
    .controls
      = f.select(:kind, options_for_select( ['web', 'imp'], 'web' ) )
  .control-group
    = f.label :image, :class => 'control-label'
    .controls
      = f.file_field :image, :class => 'file_field'
  = f.fields_for :screenshots do |screenshot_form|
    .control-group
      = screenshot_form.label :screenshot, :class => 'control-label'
      .controls
        = screenshot_form.file_field :screenshot, :class => 'file_field'
    .form-actions
      = screenshot_form.link_to_remove "Removes this screenshot", :class => 'btn'
  .form-actions
    = f.link_to_add "Add Screenshot", :screenshots, :class => 'btn'

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), projects_path, :class => 'btn'

app/views/projects/index.html.haml
#preload-p

- model_class = Project
// encabezado(img root, page main title, page secondary title, bootstrap class)
= encabezado('img-projects-page.jpg', I18n.t('projects.title'), 'false', 'span12')


.row-fluid
  #portafolio-wrapper.span12
    = render 'list'

-#
  .page-header
    %h1=t '.title', :default => model_class.model_name.human.pluralize
  %table.table.table-striped
    %thead
      %tr
        %th= model_class.human_attribute_name(:id)
        %th= model_class.human_attribute_name(:name)
        %th= model_class.human_attribute_name(:client)
        %th= model_class.human_attribute_name(:launched)
        %th= model_class.human_attribute_name(:areas)
        %th= model_class.human_attribute_name(:tecnologies)
        %th= model_class.human_attribute_name(:description)
        %th= model_class.human_attribute_name(:url)
        %th= model_class.human_attribute_name(:kind)
        %th= model_class.human_attribute_name(:created_at)
        %th=t '.actions', :default => t("helpers.actions")
    %tbody
      - @projects.each do |project|
        %tr
          %td= link_to project.id, project_path(project)
          %td= project.name
          %td= project.client
          %td= project.launched
          %td= project.areas
          %td= project.tecnologies
          %td= project.description
          %td= project.url
          %td= project.kind
          %td=l project.created_at
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_project_path(project), :class => 'btn btn-mini'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(project), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

  = link_to t('.new', :default => t("helpers.links.new")), new_project_path, :class => 'btn btn-primary'

app/views/projects/show.html.haml
- model_class = Project

// encabezado(img root, page main title, page secondary title, bootstrap class)
= encabezado(@project.image_url(:parallax), @project.name, 'false', 'span10 offset1')

#proyect-actions.row
  .span12
    = link_to image_tag('flecha-izquierda.png'), @project.previous_project, id: 'flecha-izquierda' if @project.previous_project
    = link_to image_tag('flecha-derecha.png'), @project.next_project, id: 'flecha-derecha' if @project.next_project
.row
  .span6
    = render 'bootstrap_slider'
  .span6
    .dato
      %b Fecha:
      %p
        = l @project.launched, :format => :month

    .dato
      %b Cliente:
      %p
        = @project.client

    .dato
      %b Áreas:
      %p
        = @project.areas

    .dato
      %b Tecnología:
      %p
        = @project.tecnologies
    %hr
    = paragraph(@project.description)

    - unless @project.url.empty?
      %p.proyect-links
        %span.link-label
          Visita la web
        = link_to @project.url, @project.url, target: '_blank', class: 'btn external'

- if current_admin
  .form-actions
    = link_to t('.back', :default => t("helpers.links.back")), projects_path, :class => 'btn'
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_project_path(@project), :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(@project), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/questions/edit.html.haml
%h1= t '.title'
%p
  = link_to t('back'), questions_path
  = link_to t('show'), @question
= render 'form'

app/views/questions/index.html.haml
#preload-q

- model_class = Question
// encabezado(img root, page main title, page secondary title, bootstrap class)
= encabezado('img-questions-page.jpg', I18n.t('questions.title'), 'false', 'span12')

.row-fluid
  #questions-wrapper.span12
    %p.lead La duda es uno de los nombres de la inteligencia.
    Jorge Luis Borges.
    .accordion#accordion2
      - @questions.each_with_index do |question, index|
        .accordion-group
          .accordion-heading
            %a{:class => 'accordion-toggle', :data => {'toggle' => 'collapse', 'parent' => '#accordion2'  }, :href => "#collapseOne-#{index}" }
              %h2  
                = question.question
            %div{:id => "collapseOne-#{index}", :class => 'accordion-body collapse'}
              .accordion-inner
                %p
                  = question.answer
      - if current_admin
        .action= link_to t('show'), question
        .action= link_to t('edit'), edit_question_path(question)
        .action= link_to t('destroy'), question, :confirm => ('¿Estás seguro?'), :method => :delete

app/views/questions/new.html.haml
%h1= t '.title'
%p= link_to t('back'), questions_path
= render 'form'

app/views/questions/show.html.haml
%h1= t '.title'
%p
  = link_to t('back'), questions_path
  = link_to t('edit'), edit_question_path(@question)

%dl
  %dt= Question.human_attribute_name :question
  %dd= @question.question
  %dt= Question.human_attribute_name :answer
  %dd= @question.answer